# Generated by Django 5.2.1 on 2025-05-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoardSettings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsearchsetting',
            name='location',
        ),
        migrations.AddField(
            model_name='leadsearchsetting',
            name='per_page',
            field=models.IntegerField(default=20),
        ),
    ]
