# Generated by Django 5.2.1 on 2025-05-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoardSettings', '0002_remove_leadsearchsetting_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsearchsetting',
            name='lead_source',
        ),
    ]
