# Generated by Django 5.2.1 on 2025-05-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoardSettings', '0004_apikey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadsearchsetting',
            old_name='radius_miles',
            new_name='numbLeads',
        ),
        migrations.RemoveField(
            model_name='leadsearchsetting',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='leadsearchsetting',
            name='per_page',
        ),
    ]
