# Generated by Django 5.2.1 on 2025-05-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoardSettings', '0005_rename_radius_miles_leadsearchsetting_numbleads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsearchsetting',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
