# Generated by Django 5.2.1 on 2025-05-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_address_alter_lead_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('ai', 'AI'), ('google', 'Google')], default='website', max_length=20),
        ),
    ]
