# Generated by Django 5.2.1 on 2025-05-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_email',
            field=models.EmailField(blank=True, max_length=20),
        ),
    ]
