# Generated by Django 5.2.1 on 2025-05-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='company_email',
        ),
        migrations.AddField(
            model_name='lead',
            name='company_website',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
