# Generated by Django 5.2.1 on 2025-05-28 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_remove_lead_company_email_lead_company_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='company_phone',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone',
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='LeadEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='leads.lead')),
            ],
        ),
    ]
