# Generated by Django 5.2.1 on 2025-05-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_remove_lead_company_phone_remove_lead_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='logo',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lead',
            name='types',
            field=models.TextField(blank=True, null=True),
        ),
    ]
