# Generated by Django 5.2.1 on 2025-05-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_logo_lead_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
