# Generated by Django 5.2.1 on 2025-05-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
